services:
  web:
    restart: always
    build:
      context: ../src/
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "${WEBSITE_PORT}:5000"
    volumes:
      - ../src:/app
